# Generated by Django 3.2.9 on 2021-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_user',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
