# Generated by Django 3.2.9 on 2021-11-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(limit_choices_to={'id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myapp.author'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=120)),
                ('books_available', models.ForeignKey(limit_choices_to={'available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_books', to='myapp.book')),
            ],
        ),
    ]
