# Generated by Django 3.2.9 on 2021-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_blog_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_publicity',
            field=models.DateField(null=True),
        ),
    ]
